katalog/urls.py
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import show_create_task
from todolist.views import show_todolist
from todolist.views import update_status
from todolist.views import delete
from todolist.views import show_json
from todolist.views import show_add_task
from todolist.views import delete_task

app_name = 'todolist'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', show_create_task, name='create-task'),
    path('', show_todolist, name='todolist'),
    path('update_status/<int:id>/', update_status, name='update_status'),
    path('delete/<int:id>/', delete, name='delete'),
    path('json/', show_json, name='json'),
    path('add/', show_add_task, name='add-task'),
    path('delete-task/<int:id>/', delete_task, name='delete-task'),
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

class TaskList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms

class TaskForm(forms.Form):
    title = forms.CharField(label="Enter your task!", max_length=255)
    description = forms.CharField(label="Describe your task!", widget=forms.Textarea)

todolist/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
from django.http.response import JsonResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from todolist.models import TaskList
from todolist.forms import TaskForm
import datetime

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_todolist = TaskList.objects.filter(user=request.user)
    context = {
    'data_todolist': data_todolist,
    'username': request.user.get_username(),
    }
    return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def show_json(request):
    data_todolist = TaskList.objects.filter(user=request.user)   
    return HttpResponse(serializers.serialize('json', data_todolist), content_type="application/json")

@login_required(login_url='/todolist/login/')
def show_add_task(request):
    if request.method == 'POST':
        user = request.user
        date = datetime.datetime.now()
        title = request.POST.get('title')
        description = request.POST.get('description')
        is_finished = False
        TaskList.objects.create(date=date, user=user, title=title, description=description, is_finished=is_finished)
        return JsonResponse({"Message": 'Your new task has been added!'},status=200)
    return redirect('todolist:todolist')

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account has been created successfully!')
            return redirect('todolist:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('todolist:todolist')
        else:
            messages.info(request, 'Wrong Username or Password!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('todolist:login')

@login_required(login_url='/todolist/login/')
def show_create_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            user = request.user
            date = datetime.datetime.now()
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            is_finished = False
            TaskList.objects.create(date=date, user=user, title=title, description=description, is_finished=is_finished)
            messages.success(request, 'Your new task has been added!')
            return redirect('todolist:todolist')
    else:
        form = TaskForm()
    return render(request, 'create-task.html', {'form': form, 'username': request.user.get_username()} )

@login_required(login_url='/todolist/login/')
def update_status(request, id):
    data = TaskList.objects.get(user = request.user, pk = id)
    data.is_finished = not data.is_finished
    data.save()
    return redirect('todolist:todolist')

@login_required(login_url='/todolist/login/')
def delete(request, id):
    data = TaskList.objects.get(user = request.user, pk = id)
    data.delete()
    messages.success(request, 'Your task has been successfully deleted!')
    return redirect('todolist:todolist')

@login_required(login_url='/todolist/login/')
def delete_task(request, id):
    data = TaskList.objects.get(user = request.user, pk = id)
    data.delete()
    return JsonResponse({"Message": 'Your task has been successfully deleted!'},status=200)

todolist/templates/create-task.html
{% extends 'base.html' %}

{% block meta %}

    <title>Create Task</title>

{% endblock meta %}

{% block content %}

    <nav class="navbar">
        <div class="container-fluid">
        <span class="navbar-brand mb-0 h1">Welcome {{username}}! </span>
        <div class="d-flex" >
            <button class="btn btn-outline-success me-2" type="button"><a href="{% url 'todolist:todolist' %}">Home</a></button>
        </div>
        </div>
    </nav>

    <div class = "create-task">

        <br>
        <h1>Create Task</h1>

        <div class = "containerC">
            <div class = "formT">
                <form action="" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class= "fieldWrapper">
                            <br>
                            <div class = "inputT">{{ field.label_tag }}</div>
                            <div class = "inputT">{{ field }}</div>
                        </div>
                    {% endfor %}
                    <br>
                    <input id ="btn" type="submit" value="Daftar">
                    <br></br>
                </form>
            </div>
        </div>    
    </div>
</body>
    {% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}

    <title>Login</title>

{% endblock meta %}

{% block content %}

<div class = "login">

    <div class="containerL">
        <div class="formL">
            <form method="POST" action="">
                {% csrf_token %}
                <br>
                <table id = "login">
                    <tr>
                        <td>Username: <input class="inputL" type="text" name="username" placeholder="Username" class="form-control"></td>
                    </tr>

                    <tr>
                        <td>Password: <input class="inputL" type="password" name="password" placeholder="Password" class="form-control"></td>
                    </tr>
                    <tr>
                        <td> </td>
                    </tr>
                    <tr>
                        <td><input class="login_btn" type="submit" value="Login"></td>
                    </tr>
                </table>
            </form> 
            {% if messages %}
                <ul class = "messageL">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %} 
            
            <br>
            <p class = "p"> Don't have an account yet? <a href="{% url 'todolist:register' %}">Create account</a></p>
        </div>
    </div>


</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}

<title>Registrasi Akun</title>

{% endblock meta %}

{% block content %}  

    <div class = "register"> 
        <div class = "containerR">
            <div class = "formR">
                <form method="POST" >  
                    {% csrf_token %}  
                    <br></br> 
                    {% for field in form %}
                    <div>
                        <div class = "inputR">{{ field.label_tag }} {{ field }}</div>
                        <div class = "inputR" id="help">{{ field.help_text }}</div>
                        <br>
                    </div>
                    <div class = "messageR">{{  field.errors }}</div>
                    {% endfor %}
                    <input class ="daftar_btn" type="submit" value="Register">           
                </form>
                <br>
                <p class = "p"> Already have an account? <a href="{% url 'todolist:login' %}">Login here!</a></p>
            </div>
        </div>

    </div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}

    <style>
        #btnA {
        width: 120px;
        margin-top: auto;
        margin-bottom: auto;
        margin-left: auto;
        margin-right: auto;
        background-color: #d28542;
        padding: 5px 15px;
        border-radius: 15px;
        color: white;
        font: bold;
        font-size: 15px;
    }

        #btnA:hover {
            box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
        }
        
    </style>

    <title> Home </title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
    
        function load(data) {
            let card = ``;
    
            for (let i of data) {

                let is_finished_status = i.fields.is_finished ? "Finished" : "Haven't Finish"

                card += `
                    <div id="${i.pk}" class="card shadow p-3 mb-5 bg-body rounded mx-3 my-4 mouse">
                        <div class="card" style="width: 19rem; height: 100%;">
                            <div class="card-body">
                                <div>
                                    <button id ="btn-ans"><a href="/todolist/update_status/${i.pk}">${is_finished_status}</a></button>
                                    <button id ="btn-ans" onclick= "delete_task(${i.pk})">Delete</button>
                                </div>
                                <br>
                                <small class="card-subtitle mb-2 text-muted">${i.fields.date}</small>
                                <h5 class="card-title">${i.fields.title}</h5>
                                <p class="card-text tex-truncate">${i.fields.description}</p>
                            </div>
                        </div>
                    </div>
                `;
            }
    
            document.getElementById("make-card").innerHTML = card;
        }

        function refresh() {
            $.get("{% url 'todolist:json' %}", function (data) {
                load(data);
            });
        }
     
        $(document).ready(function () {
            refresh();
        });

        function submitTask() {
            $.ajax({
                type: "POST",
                url: "{% url 'todolist:add-task' %}",
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    title: $("#title").val(),
                    description: $("#description").val(),
                },
                dataType: "json",
                success: function () {
                    refresh();
                    $("#addModal").modal('hide')
                    document.getElementById("title").value = "";
                    document.getElementById("description").value = "";
                },
            });
        }
        
        function delete_task(id){
            $.ajax({
                type: "GET",
                url: "/todolist/delete-task/" + id,
                data: {csrfmiddlewaretoken: "{{ csrf_token }}"},
                dataType: "json",
                success: function () {
                    refresh();
                }
            })
        }
    
    </script>

{% endblock meta %}

{% block content %}

    <nav class="navbar">
        <div class="container-fluid">
          <span class="navbar-brand mb-0 h1">Welcome {{username}}! </span>
          <div class="d-flex" >
            <button class="btn btn-outline-success me-2" type="button"><a href="{% url 'todolist:logout' %}">Logout</a></button>
          </div>
        </div>
    </nav>

    <br>
    <h2>To Do List Generator</h2>
    <p class = "p">Tugas 4 Assignment PBP/PBD</p>

    <br>

    <div class = "button">
        <button type="button" class = btn-create data-bs-toggle="modal" data-bs-target="#addModal">Add Task</button>
    </div>

    <br>

    {% if messages %}  
    <ul class = "messageT">   
        {% for message in messages %}  
            <li>{{ message }}</li>  
            {% endfor %}  
    </ul>   
    {% endif %}

    <div class="d-flex flex-wrap justify-content-center" id="make-card"></div>

    <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">New Task</h5>
            </div>
            <div class="modal-body">
              <form id="formA" method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <label for="recipient-name" class="col-form-label">Title:</label>
                  <input type="text" class="form-control" id="title">
                </div>
                <div class="form-group">
                  <label for="message-text" class="col-form-label">Description:</label>
                  <textarea class="form-control" id="description"></textarea>
                </div>
              </form>
            </div>
            <div class="modal-footer">
              <button id="btnA" type="submit" value="Submit" onclick="submitTask()">Submit</button>
            </div>
          </div>
        </div>
    </div>

{% endblock content%}